# FARM HEADER FILE


# ----WINDOW SIZES & POSITIONS -----

SUNRISE_DIR='GRAPHICS/SUNRISE2/'

GAME_WIN_SIZE_Y=33
GAME_WIN_SIZE_X=66
GAME_WIN_POS_Y=4
GAME_WIN_POS_X=0

MSG_WIN_SIZE_Y=3
MSG_WIN_SIZE_X=66
MSG_WIN_POS_Y=0
MSG_WIN_POS_X=0

TXT_WIN_SIZE_Y=6
TXT_WIN_SIZE_X=29
TXT_WIN_POS_Y=13
TXT_WIN_POS_X=19

HELP_WIN_SIZE_Y=10
HELP_WIN_SIZE_X=22
HELP_WIN_POS_Y=20
HELP_WIN_POS_X=22

# ----CONTROL KEYS-------

KEY_UP=ord('w')
KEY_DOWN=ord('s')
KEY_LEFT=ord('a')
KEY_RIGHT=ord('d')
NULL='NULL'

KEY_INTERACT=ord('k')
KEY_PLANT=ord('p')
KEY_HARVEST=ord('h')
KEY_INVENTORY=ord('i')

KEY_QUIT=ord('q')

# ---- ENVIRONMENT VARIABLES ----

ALL_VISIBLE=False
VIEW_DISTANCE_Y=5
VIEW_DISTANCE_X=8

HOUSE_GRAPHIC='GRAPHICS/house'
SHIP_BOX_GRAPHIC='GRAPHICS/ship_box'
POND_GRAPHIC='GRAPHICS/pond1'

NUMBER_TREES=18
NUMBER_ROCKS=13

PLAYER_1_GRAPHIC='@'
PLAYER_1_START_POS=[6, 6]

DOG_GRAPHIC='d'
DOG_START_POS=[7, 8]

